spring.application.name=JwtDemo
#JWT
jwt.secret=
jwt.access-token-expiration=900000
# 15 minut = 15 * 50 * 1000 = 900 000 milisecunden
jwt.refresh-token-expiration=604800000
# 7 days = 7 * 24 * 60 * 60 * 1000 = 604 800 000 milisecunden

# H2 Database
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa12345

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console ()
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console